### ISSUE TITLE
How did you intend tests.pages.IndexPage.isAt() to be used?

### ISSUE THREAD

**Issue by marknelsonengineer** [ics-software-engineering/play-example-fluentlenium#2]
Dr. Johnson,

I like the idea of the isAt() method in IndexPage, but:
1.  Was it your intention to embed a test in a non-test class?
2.  It appears that isAt() is never invoked.  I modified a cloned version of the repository to look like this:

```
@Override
public void isAt() {
    throw new RuntimeException("Do I ever get here?");
//assertThat(title()).isEqualTo("Index");
}
```

...then I re-ran the tests.  Unless something inside Fluentlenium absorbs the RuntimeException I suspect this method is... underutilized.

How did you intend for this method to be used?

Thank you,
Mark

**Comment by philipmjohnson** [comment]
Yes, the code is correct, though not completely illustrative.  The IndexPage class encapsulates the behavior associated with that page, and one of the required behaviors is a check to see if the browser emulator is actually on that page. (It's a required behavior by virtue of the fact that you override the default implementation with one that actually does the check.)  

Unfortunately, the code did not show an example of how the isAt() method could be used in practice, so I've added a call to it here:

https://github.com/ics-software-engineering/play-example-fluentlenium/blob/master/test/tests/IntegrationTest.java#L33

The utility of isAt() is that after attempting to "goto" a page (or arrive at a page in some other way, such as after a form submission), you can then check that you're actually on the expected page and fail the test run immediately if it didn't happen.
